version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    environment:
      TZ: Asia/Taipei

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'

  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  golang_flip:
    build:
      context: ./
      dockerfile: ./promAppD/Dockerfile
    container_name: golang_flip
    entrypoint: ./exec
    ports:
      - '9001:9001'
      
  notifyhook:
    build: 
      context: ./
      dockerfile: ./notifyHookD/Dockerfile
    container_name: notfiyHook
    entrypoint: ./exec
    ports:
      - '8001:8001'

volumes:
  prometheus_data:
  grafana_data:


